# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17i7VYx8AciC3YiMgCSG2LIEUOUD9Wrc4

***LETS GROW MORE INTERNSHIP PROGRAM ***
**JUNE 2023**

**TASK 1: IRIS FLOWER CLASSIFICATION MACHINE LEARNING MODEL**

**BY - AKSHITA SHRIVASTAVA**

**IMPORTING LIBRARIES::**
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn import svm, datasets
from types import UnionType
# %matplotlib inline

"""Load datasets in tabular form:"""

df = pd.read_csv('Iris.csv')
df.head()

"""To delete a column

"""

df = df.drop(columns = ['Species'])
df.head()

"""Loading the statistics of the data frame

Observing the distributions in tabular form
"""

df.describe()

df.shape

"""Information about the model

"""

df.info

"""Display of samples of each class"""

df['SepalLengthCm'].value_counts()

"""Check for Null Values"""

df.isnull().sum()

df.nunique()

"""ANALYSING DATASETS:

"""

df.columnsANALYSING DATASETS:

"""Histogram representation of specific columns:"""

df['SepalLengthCm'].hist()

df['PetalWidthCm'].hist()

df['SepalWidthCm'].hist()

df['PetalLengthCm'].hist()

"""Demonstrating all columns in one graph


1.   Histogram Style


"""

df['PetalLengthCm'].hist()
df['SepalLengthCm'].hist()
df['PetalWidthCm'].hist()
df['SepalWidthCm'].hist()

"""
2. Area Plot Style

"""

df.plot.area(figsize = (5,5), stacked = False)

"""3. Scatter Plot

"""

for i in df.columns:
[ ]
for i in df.columns:
  plt.scatter(df[str(i)], df['SepalLengthCm'])
  plt.xlabel(i)
  plt.ylabel('PetalWidthcm')
  plt.show()

  plt.scatter(df[str(i)], df['SepalLengthCm'])
  plt.xlabel(i)
  plt.ylabel('PetalWidthcm')
  plt.show()

"""Seaborn Plot"""

colors = ['blue', 'yellow' 'red']
SepalLengthcm = [8.000000, 23.271425, 51.247113, 0.828066, 4.900000 ]

"""CORELATION OF DATASETS:

"""

df.corr()

"""Graphical Representation of correlation of datasets ::"""

plt.figure(figsize = (12,14))
sns.heatmap(df.corr(), cmap ='Oranges',annot = True)

"""CONCLUSIONS:

"""